import type { WeaponConfig } from '@/types/combat';

export const WEAPONS: Record<string, WeaponConfig> = {
  pistol: {
    id: 'pistol',
    name: 'Pistol',
    damage: 20,
    fireRate: 3,
    magazineSize: 12,
    reloadTime: 1500,
    projectileSpeed: 900,
    projectileCount: 1,
    spread: 0,
    range: 1200,
    automatic: false,
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 15,
    fireRate: 1,
    magazineSize: 6,
    reloadTime: 2500,
    projectileSpeed: 700,
    projectileCount: 6,
    spread: 18,
    spreadRandom: 4,
    range: 450,
    automatic: false,
  },
  assault_rifle: {
    id: 'assault_rifle',
    name: 'Assault Rifle',
    damage: 18,
    fireRate: 8,
    magazineSize: 30,
    reloadTime: 2000,
    projectileSpeed: 1100,
    projectileCount: 1,
    spread: 3,
    range: 1400,
    automatic: true,
  },
};
